= Kafka Cheat Sheet
:toc:
:toc-placement!:

Here you have some useful commands for kafka.

Tested on Kafka 2.5

toc::[]

== Pre-req

First, set some kafka environment vars.

[source,bash]
----
KAFKA_BIN=/opt/kafka/bin
ZOOKEEPER_HOST=zookeeper-host:2181
BROKER_HOST=broker-host:9092
----

== Zookeeper Operations

You need to whitelist all the commands bellow. 

.zookeeper.properties
----
4lw.commands.whitelist=stat,ruok,reqs,envi,dump,conf,cons,srvr,wchs,wchc,dirs,wchp,mntr,isro
----

If using Zookeeper Auth

----
# Zookeeper Auth
KAFKA_OPTS="-Djava.security.auth.login.config=/tmp/jaas.conf"
----

.jass.conf
----
Client {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       username="test"
       password="test";
};
----

=== Get runtime conf

[source,bash]
----
echo conf | curl telnet://$ZOOKEEPER_HOST
----

=== Get runtime environments

[source,bash]
----
echo envi | curl telnet://$ZOOKEEPER_HOST
----

=== Health Check

[source,bash]
----
echo stats | curl telnet://$ZOOKEEPER_HOST

echo ruok | curl telnet://$ZOOKEEPER_HOST
----

=== Connections

[source,bash]
----
echo reqs | curl telnet://$ZOOKEEPER_HOST

echo cons | curl telnet://$ZOOKEEPER_HOST
----

=== Details of the server

[source,bash]
----
echo srvr | curl telnet://$ZOOKEEPER_HOST
----

=== Brief info about watches

[source,bash]
----
echo wchs | curl telnet://$ZOOKEEPER_HOST
----

=== Details about watches

[source,bash]
----
echo wchc | curl telnet://$ZOOKEEPER_HOST
----

=== Snapshots info

[source,bash]
----
echo dirs | curl telnet://$ZOOKEEPER_HOST
----

=== Monitoring vars

[source,bash]
----
echo mntr | curl telnet://$ZOOKEEPER_HOST
----

=== Get read-only or read-write mode

[source,bash]
----
echo isro | curl telnet://$ZOOKEEPER_HOST
----

=== Get Process

[source,bash]
----
jps | grep QuorumPeerMain
----

== Broker Operations

=== List active brokers

[source,bash]
----
$KAFKA_BIN/zookeeper-shell.sh $ZOOKEEPER_HOST ls /brokers/ids
----

=== List broker details

[source,bash]
----
$KAFKA_BIN/zookeeper-shell.sh $ZOOKEEPER_HOST ls /brokers/ids/{id}
----

=== List topics

[source,bash]
----
$KAFKA_BIN/zookeeper-shell.sh $ZOOKEEPER_HOST ls /brokers/topics
----

== Topic Operations

=== List topics using kafka-topics.sh

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --list \
    --zookeeper $ZOOKEEPER_HOST
----

=== Describe topic

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --topic <topic_name> \
    --describe
----

=== Create topic

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --create \
    --zookeeper $ZOOKEEPER_HOST \
    --replication-factor 1 \
    --partitions 1 \
    --topic <topic_name>
----

=== Alter topic

==== Alter retention time

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --alter \
    --topic <topic_name>\
    --config retention.ms=1000
----

==== Alter min.insync.replicas

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --alter \
    --topic <topic_name> \
    --config min.insync.replicas=2
----

==== Delete retention time

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --alter \
    --topic <topic_name> \
    --delete-config retention.ms
----

=== List topics under-replicated

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --describe \
    --under-replicated-partitions
----

=== Delete topic

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --delete \
    --zookeeper $ZOOKEEPER_HOST \
    --topic <topic_name>
----

=== Get earliest offset

[source,bash]
----
$KAFKA_BIN/kafka-run-class.sh \
    kafka.tools.GetOffsetShell \
    --broker-list $BROKER_HOST \
    --topic <topic_name> \
    --time -2
----

=== Get latest offset

[source,bash]
----
$KAFKA_BIN/kafka-run-class.sh \
    kafka.tools.GetOffsetShell \
    --broker-list $BROKER_HOST \
    --topic <topic_name> \
    --time -1
----

== Partition Operations

=== Add partitions

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --alter \
    --topic <topic_name> \
    --partitions 8
----

=== Reassign partitions

[source,bash]
----
$KAFKA_BIN/kafka-reassign-partitions.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --reassignment-json-file increase-replication-factor.json  \
    --execute

$KAFKA_BIN/kafka-reassign-partitions.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --reassignment-json-file increase-replication-factor.json  \
    --verify
----

=== List unavailable partitions

[source,bash]
----
$KAFKA_BIN/kafka-topics.sh \
    --zookeeper $ZOOKEEPER_HOST \
    --describe \
    --unavailable-partitions
----

== Consumer

=== List consumer groups

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --list \
    --bootstrap-server $BROKER_HOST
----

=== Describe consumer groups

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --describe \
    --group <group_id> \
    --bootstrap-server $BROKER_HOST
----

=== Consuming message from the beginning

[source,bash]
----
$KAFKA_BIN/kafka-console-consumer.sh \
    --bootstrap-server $BROKER_HOST \
    --topic <topic_name> \
    --from-beginning
----

=== Consuming message from the end

[source,bash]
----
$KAFKA_BIN/kafka-console-consumer.sh \
    --bootstrap-server $BROKER_HOST \
    --topic <topic_name>
----

=== Read one message

[source,bash]
----
$KAFKA_BIN/kafka-console-consumer.sh \
    --bootstrap-server $BROKER_HOST \
    --topic <topic_name> \
    --max-messages 1
----

=== Read from __consumer_offsets

[source,bash]
----
$KAFKA_BIN/kafka-console-consumer.sh \
    --bootstrap-server $BROKER_HOST \
    --topic __consumer_offsets \
    --formatter 'kafka.coordinator.group.GroupMetadataManager$OffsetsMessageFormatter' \
    --max-messages 1
----

=== Consume using consumer group

[source,bash]
----
$KAFKA_BIN/kafka-console-consumer.sh \
    --topic <topic_name> \
    --bootstrap-server $BROKER_HOST \
    --group <group-id>
----

=== Topics to which group is subscribed

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --group <group_id> \
    --describe
----

=== Reset offset

==== Reset offset for a consumer group in a topic

[source,bash]
----
# There are many other resetting options
# --shift-by <positive_or_negative_integer> / --to-current / --to-latest / --to-offset <offset_integer>
# --to-datetime <datetime_string> --by-duration <duration_string>
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --group <group_id> \
    --topic <topic_name> \
    --reset-offsets \
    --to-earliest \
    --execute
----

==== Reset offset from all consumer groups

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --all-groups \
    --reset-offsets \
    --topic <topic_name> \
    --to-earliest
----

==== Forward by 2 for example

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --group <groud_id> \
    --reset-offsets \
    --shift-by 2 \
    --execute \
    --topic <topic_name>
----

==== Backward by 2 for example

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --group <groud_id> \
    --reset-offsets \
    --shift-by -2 \
    --execute \
    --topic <topic_name>
----

=== Describe consumer group

[source,bash]
----
$KAFKA_BIN/kafka-consumer-groups.sh \
    --bootstrap-server $BROKER_HOST \
    --describe \
    --group <group_id>
----

=== Check offset for consumer group

[source,bash]
----
$KAFKA_BIN/kafka-consumer-offset-checker.sh  \
    --zookeeper $ZOOKEEPER_HOST \
    --group <group_id> \
    --topic <topic_name>
----

== Producer

=== Send message using file

[source,bash]
----
$KAFKA_BIN/kafka-console-producer.sh \
    --broker-list $BROKER_HOST \
    --topic <topic_name> < messages.txt
----

=== Send message using standard input

[source,bash]
----
$KAFKA_BIN/kafka-console-producer \
    --broker-list $BROKER_HOST \
    --topic <topic_name>
----

=== Send message using string

[source,bash]
----
echo "My Message" | $KAFKA_BIN/kafka-console-producer.sh \
    --broker-list $BROKER_HOST \
    --topic <topic_name>
----

=== Send message using ack=all

[source,bash]
----
$KAFKA_BIN/kafka-console-producer.sh \
    --broker-list $BROKER_HOST \
    --topic <topic_name> \
    --producer-property acks=all
----

== ACLs

[source,bash]
----
$KAFKA_BIN/kafka-acls.sh \
    --authorizer-properties zookeeper.connect=$ZOOKEEPER_HOST \
    --add \
    --allow-principal User:Gus \
    --consumer \
    --topic <topic_name> \
    --group <group_id>
----

[source,bash]
----
$KAFKA_BIN/kafka-acls.sh
    --authorizer-properties zookeeper.connect=$ZOOKEEPER_HOST \
    --add \
    --allow-principal User:Gus \
    --producer \
    --topic <topic_name>
----

=== List topics ACLs

[source,bash]
----
$KAFKA_BIN/kafka-acls.sh \
    --authorizer-properties zookeeper.connect=$ZOOKEEPER_HOST \
    --list \
    --topic <topic_name>
----
